# Site settings
title: "Nick's Website"
email: nickscupofwords@gmail.com
url: https://cunningham.github.io
description: "I'm leaving Facebook so if you want to follow me you got Twitter or this!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 7EB7D6 #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Nick Cunningham
  location: Portland, OR
  social: Social

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/nickscupofwords
  - title: github
    url: http://github.com/cunningham
  - title: instagram
    url: http://instagram.com/oneslypig

# Postal address (add as many lines as necessary)
address:
  - line: 

# Credits content
credits: 'I use <a href="https://pages.github.com/">Github Pages</a> and <a href="http://jekyllrb.com/">Jekyll</a>(with the <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer theme</a> to make this site.'

# Build settings
markdown: kramdown
permalink: pretty
