# Site settings
title: "Nick's Website"
email: nickscupofwords@gmail.com
url: https://cunningham.github.io
description: "I'm leaving Facebook so if you want to follow me you got Twitter or this!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 7EB7D6 #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Nick Cunningham
  location: Portland, OR
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/nickscupofwords
  - title: facebook
    url:
  - title: github
    url: http://github.com/cunningham

# Postal address (add as many lines as necessary)
address:
  - line: 

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
